package com.infovault.model;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

// Java package used for mapping Java objects to database tables
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import java.time.LocalDateTime;

@Entity // Maps class to a database table
@Table(name = "users") // Specifies the table name in the database
public class User {

    @Id // Marks Id field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the Id field is auto-generated by the database
    private Long userId; // Stores unique identifier for user

    // Stores the rest of the user's pertinent info
    @Column(nullable = false) // Specifies that the firstName field cannot be null
    private String firstName;

    @Column(nullable = false) // Specifies that the lastName field cannot be null
    private String lastName;

    @Column(nullable = false, unique = true) // Specifies that the email field must be unique and cannot be null
    private String email;

    @Column(name = "phone_number")  // Specifies that the phoneNumber field cannot be null
    private String phoneNumber;

    @Column
    private String passwordHash; // Password should be encrypted in a real application

    @Column
    private Boolean isCognitoUser = false; // Indicates if the user is a federated user

    @Column
    private String cognitoUsername; // Stores the user's cognito user ID

    @Column(nullable = false) // Specifies that the createdAt field cannot be null
    private LocalDateTime createdAt = LocalDateTime.now(); // Stores the timestamp when the user was created

    private LocalDateTime lastLogin; // Stores the timestamp of the user's last login

    // Getters and Setters
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    // Method to set and hash the password for non-Cognito users
    public void setPasswordHash(String password) {
        if (!isCognitoUser) {
            PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
            this.passwordHash = passwordEncoder.encode(password);
        }
    }

    public Boolean getIsCognitoUser() {
        return isCognitoUser;
    }

    public void setIsCognitoUser(Boolean isCognitoUser) {
        this.isCognitoUser = isCognitoUser;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(LocalDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    public String getCognitoUsername() {
        return cognitoUsername;
    }

    public void setCognitoUsername(String cognitoUsername) {
        this.cognitoUsername = cognitoUsername;
    }
}
